export const ISSUES_UPDATE_LIST = 'ISSUES_UPDATE_LIST'
export const ISSUES_UPDATE_ISSUE = 'ISSUES_UPDATE_ISSUE'
export const ISSUES_UPDATE_FETCHING = 'ISSUES_UDPATE_FETCHING'
export const ISSUES_UPDATE_OFFSET = 'ISSUES_UPDATE_OFFSET'